// Code generated by go-swagger; DO NOT EDIT.

package lm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteLogPartitionByIDParams creates a new DeleteLogPartitionByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteLogPartitionByIDParams() *DeleteLogPartitionByIDParams {
	return &DeleteLogPartitionByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteLogPartitionByIDParamsWithTimeout creates a new DeleteLogPartitionByIDParams object
// with the ability to set a timeout on a request.
func NewDeleteLogPartitionByIDParamsWithTimeout(timeout time.Duration) *DeleteLogPartitionByIDParams {
	return &DeleteLogPartitionByIDParams{
		timeout: timeout,
	}
}

// NewDeleteLogPartitionByIDParamsWithContext creates a new DeleteLogPartitionByIDParams object
// with the ability to set a context for a request.
func NewDeleteLogPartitionByIDParamsWithContext(ctx context.Context) *DeleteLogPartitionByIDParams {
	return &DeleteLogPartitionByIDParams{
		Context: ctx,
	}
}

// NewDeleteLogPartitionByIDParamsWithHTTPClient creates a new DeleteLogPartitionByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteLogPartitionByIDParamsWithHTTPClient(client *http.Client) *DeleteLogPartitionByIDParams {
	return &DeleteLogPartitionByIDParams{
		HTTPClient: client,
	}
}

/*
DeleteLogPartitionByIDParams contains all the parameters to send to the API endpoint

	for the delete log partition by Id operation.

	Typically these are written to a http.Request.
*/
type DeleteLogPartitionByIDParams struct {

	// UserAgent.
	//
	// Default: "Logicmonitor/GO-SDK"
	UserAgent *string

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete log partition by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteLogPartitionByIDParams) WithDefaults() *DeleteLogPartitionByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete log partition by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteLogPartitionByIDParams) SetDefaults() {
	var (
		userAgentDefault = string("Logicmonitor/GO-SDK")
	)

	val := DeleteLogPartitionByIDParams{
		UserAgent: &userAgentDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the delete log partition by Id params
func (o *DeleteLogPartitionByIDParams) WithTimeout(timeout time.Duration) *DeleteLogPartitionByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete log partition by Id params
func (o *DeleteLogPartitionByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete log partition by Id params
func (o *DeleteLogPartitionByIDParams) WithContext(ctx context.Context) *DeleteLogPartitionByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete log partition by Id params
func (o *DeleteLogPartitionByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete log partition by Id params
func (o *DeleteLogPartitionByIDParams) WithHTTPClient(client *http.Client) *DeleteLogPartitionByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete log partition by Id params
func (o *DeleteLogPartitionByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserAgent adds the userAgent to the delete log partition by Id params
func (o *DeleteLogPartitionByIDParams) WithUserAgent(userAgent *string) *DeleteLogPartitionByIDParams {
	o.SetUserAgent(userAgent)
	return o
}

// SetUserAgent adds the userAgent to the delete log partition by Id params
func (o *DeleteLogPartitionByIDParams) SetUserAgent(userAgent *string) {
	o.UserAgent = userAgent
}

// WithID adds the id to the delete log partition by Id params
func (o *DeleteLogPartitionByIDParams) WithID(id string) *DeleteLogPartitionByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete log partition by Id params
func (o *DeleteLogPartitionByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteLogPartitionByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.UserAgent != nil {

		// header param User-Agent
		if err := r.SetHeaderParam("User-Agent", *o.UserAgent); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
