// Code generated by go-swagger; DO NOT EDIT.

package lm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetJobMonitorListJSONParams creates a new GetJobMonitorListJSONParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetJobMonitorListJSONParams() *GetJobMonitorListJSONParams {
	return &GetJobMonitorListJSONParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetJobMonitorListJSONParamsWithTimeout creates a new GetJobMonitorListJSONParams object
// with the ability to set a timeout on a request.
func NewGetJobMonitorListJSONParamsWithTimeout(timeout time.Duration) *GetJobMonitorListJSONParams {
	return &GetJobMonitorListJSONParams{
		timeout: timeout,
	}
}

// NewGetJobMonitorListJSONParamsWithContext creates a new GetJobMonitorListJSONParams object
// with the ability to set a context for a request.
func NewGetJobMonitorListJSONParamsWithContext(ctx context.Context) *GetJobMonitorListJSONParams {
	return &GetJobMonitorListJSONParams{
		Context: ctx,
	}
}

// NewGetJobMonitorListJSONParamsWithHTTPClient creates a new GetJobMonitorListJSONParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetJobMonitorListJSONParamsWithHTTPClient(client *http.Client) *GetJobMonitorListJSONParams {
	return &GetJobMonitorListJSONParams{
		HTTPClient: client,
	}
}

/*
GetJobMonitorListJSONParams contains all the parameters to send to the API endpoint

	for the get job monitor list Json operation.

	Typically these are written to a http.Request.
*/
type GetJobMonitorListJSONParams struct {

	// UserAgent.
	//
	// Default: "Logicmonitor/GO-SDK"
	UserAgent *string

	// Format.
	Format *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get job monitor list Json params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetJobMonitorListJSONParams) WithDefaults() *GetJobMonitorListJSONParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get job monitor list Json params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetJobMonitorListJSONParams) SetDefaults() {
	var (
		userAgentDefault = string("Logicmonitor/GO-SDK")
	)

	val := GetJobMonitorListJSONParams{
		UserAgent: &userAgentDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get job monitor list Json params
func (o *GetJobMonitorListJSONParams) WithTimeout(timeout time.Duration) *GetJobMonitorListJSONParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get job monitor list Json params
func (o *GetJobMonitorListJSONParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get job monitor list Json params
func (o *GetJobMonitorListJSONParams) WithContext(ctx context.Context) *GetJobMonitorListJSONParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get job monitor list Json params
func (o *GetJobMonitorListJSONParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get job monitor list Json params
func (o *GetJobMonitorListJSONParams) WithHTTPClient(client *http.Client) *GetJobMonitorListJSONParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get job monitor list Json params
func (o *GetJobMonitorListJSONParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserAgent adds the userAgent to the get job monitor list Json params
func (o *GetJobMonitorListJSONParams) WithUserAgent(userAgent *string) *GetJobMonitorListJSONParams {
	o.SetUserAgent(userAgent)
	return o
}

// SetUserAgent adds the userAgent to the get job monitor list Json params
func (o *GetJobMonitorListJSONParams) SetUserAgent(userAgent *string) {
	o.UserAgent = userAgent
}

// WithFormat adds the format to the get job monitor list Json params
func (o *GetJobMonitorListJSONParams) WithFormat(format *string) *GetJobMonitorListJSONParams {
	o.SetFormat(format)
	return o
}

// SetFormat adds the format to the get job monitor list Json params
func (o *GetJobMonitorListJSONParams) SetFormat(format *string) {
	o.Format = format
}

// WriteToRequest writes these params to a swagger request
func (o *GetJobMonitorListJSONParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.UserAgent != nil {

		// header param User-Agent
		if err := r.SetHeaderParam("User-Agent", *o.UserAgent); err != nil {
			return err
		}
	}

	if o.Format != nil {

		// query param format
		var qrFormat string

		if o.Format != nil {
			qrFormat = *o.Format
		}
		qFormat := qrFormat
		if qFormat != "" {

			if err := r.SetQueryParam("format", qFormat); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
