// Code generated by go-swagger; DO NOT EDIT.

package lm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetOIDListJSONParams creates a new GetOIDListJSONParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOIDListJSONParams() *GetOIDListJSONParams {
	return &GetOIDListJSONParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOIDListJSONParamsWithTimeout creates a new GetOIDListJSONParams object
// with the ability to set a timeout on a request.
func NewGetOIDListJSONParamsWithTimeout(timeout time.Duration) *GetOIDListJSONParams {
	return &GetOIDListJSONParams{
		timeout: timeout,
	}
}

// NewGetOIDListJSONParamsWithContext creates a new GetOIDListJSONParams object
// with the ability to set a context for a request.
func NewGetOIDListJSONParamsWithContext(ctx context.Context) *GetOIDListJSONParams {
	return &GetOIDListJSONParams{
		Context: ctx,
	}
}

// NewGetOIDListJSONParamsWithHTTPClient creates a new GetOIDListJSONParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOIDListJSONParamsWithHTTPClient(client *http.Client) *GetOIDListJSONParams {
	return &GetOIDListJSONParams{
		HTTPClient: client,
	}
}

/*
GetOIDListJSONParams contains all the parameters to send to the API endpoint

	for the get o ID list Json operation.

	Typically these are written to a http.Request.
*/
type GetOIDListJSONParams struct {

	// UserAgent.
	//
	// Default: "Logicmonitor/GO-SDK"
	UserAgent *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get o ID list Json params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOIDListJSONParams) WithDefaults() *GetOIDListJSONParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get o ID list Json params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOIDListJSONParams) SetDefaults() {
	var (
		userAgentDefault = string("Logicmonitor/GO-SDK")
	)

	val := GetOIDListJSONParams{
		UserAgent: &userAgentDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get o ID list Json params
func (o *GetOIDListJSONParams) WithTimeout(timeout time.Duration) *GetOIDListJSONParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get o ID list Json params
func (o *GetOIDListJSONParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get o ID list Json params
func (o *GetOIDListJSONParams) WithContext(ctx context.Context) *GetOIDListJSONParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get o ID list Json params
func (o *GetOIDListJSONParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get o ID list Json params
func (o *GetOIDListJSONParams) WithHTTPClient(client *http.Client) *GetOIDListJSONParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get o ID list Json params
func (o *GetOIDListJSONParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserAgent adds the userAgent to the get o ID list Json params
func (o *GetOIDListJSONParams) WithUserAgent(userAgent *string) *GetOIDListJSONParams {
	o.SetUserAgent(userAgent)
	return o
}

// SetUserAgent adds the userAgent to the get o ID list Json params
func (o *GetOIDListJSONParams) SetUserAgent(userAgent *string) {
	o.UserAgent = userAgent
}

// WriteToRequest writes these params to a swagger request
func (o *GetOIDListJSONParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.UserAgent != nil {

		// header param User-Agent
		if err := r.SetHeaderParam("User-Agent", *o.UserAgent); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
