// Code generated by go-swagger; DO NOT EDIT.

package lm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetDiagnosticSourcesByIDParams creates a new GetDiagnosticSourcesByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDiagnosticSourcesByIDParams() *GetDiagnosticSourcesByIDParams {
	return &GetDiagnosticSourcesByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDiagnosticSourcesByIDParamsWithTimeout creates a new GetDiagnosticSourcesByIDParams object
// with the ability to set a timeout on a request.
func NewGetDiagnosticSourcesByIDParamsWithTimeout(timeout time.Duration) *GetDiagnosticSourcesByIDParams {
	return &GetDiagnosticSourcesByIDParams{
		timeout: timeout,
	}
}

// NewGetDiagnosticSourcesByIDParamsWithContext creates a new GetDiagnosticSourcesByIDParams object
// with the ability to set a context for a request.
func NewGetDiagnosticSourcesByIDParamsWithContext(ctx context.Context) *GetDiagnosticSourcesByIDParams {
	return &GetDiagnosticSourcesByIDParams{
		Context: ctx,
	}
}

// NewGetDiagnosticSourcesByIDParamsWithHTTPClient creates a new GetDiagnosticSourcesByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDiagnosticSourcesByIDParamsWithHTTPClient(client *http.Client) *GetDiagnosticSourcesByIDParams {
	return &GetDiagnosticSourcesByIDParams{
		HTTPClient: client,
	}
}

/*
GetDiagnosticSourcesByIDParams contains all the parameters to send to the API endpoint

	for the get diagnostic sources by Id operation.

	Typically these are written to a http.Request.
*/
type GetDiagnosticSourcesByIDParams struct {

	// UserAgent.
	//
	// Default: "Logicmonitor/GO-SDK"
	UserAgent *string

	// Format.
	Format *string

	// ID.
	//
	// Format: int32
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get diagnostic sources by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDiagnosticSourcesByIDParams) WithDefaults() *GetDiagnosticSourcesByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get diagnostic sources by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDiagnosticSourcesByIDParams) SetDefaults() {
	var (
		userAgentDefault = string("Logicmonitor/GO-SDK")
	)

	val := GetDiagnosticSourcesByIDParams{
		UserAgent: &userAgentDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get diagnostic sources by Id params
func (o *GetDiagnosticSourcesByIDParams) WithTimeout(timeout time.Duration) *GetDiagnosticSourcesByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get diagnostic sources by Id params
func (o *GetDiagnosticSourcesByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get diagnostic sources by Id params
func (o *GetDiagnosticSourcesByIDParams) WithContext(ctx context.Context) *GetDiagnosticSourcesByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get diagnostic sources by Id params
func (o *GetDiagnosticSourcesByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get diagnostic sources by Id params
func (o *GetDiagnosticSourcesByIDParams) WithHTTPClient(client *http.Client) *GetDiagnosticSourcesByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get diagnostic sources by Id params
func (o *GetDiagnosticSourcesByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserAgent adds the userAgent to the get diagnostic sources by Id params
func (o *GetDiagnosticSourcesByIDParams) WithUserAgent(userAgent *string) *GetDiagnosticSourcesByIDParams {
	o.SetUserAgent(userAgent)
	return o
}

// SetUserAgent adds the userAgent to the get diagnostic sources by Id params
func (o *GetDiagnosticSourcesByIDParams) SetUserAgent(userAgent *string) {
	o.UserAgent = userAgent
}

// WithFormat adds the format to the get diagnostic sources by Id params
func (o *GetDiagnosticSourcesByIDParams) WithFormat(format *string) *GetDiagnosticSourcesByIDParams {
	o.SetFormat(format)
	return o
}

// SetFormat adds the format to the get diagnostic sources by Id params
func (o *GetDiagnosticSourcesByIDParams) SetFormat(format *string) {
	o.Format = format
}

// WithID adds the id to the get diagnostic sources by Id params
func (o *GetDiagnosticSourcesByIDParams) WithID(id int32) *GetDiagnosticSourcesByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get diagnostic sources by Id params
func (o *GetDiagnosticSourcesByIDParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetDiagnosticSourcesByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.UserAgent != nil {

		// header param User-Agent
		if err := r.SetHeaderParam("User-Agent", *o.UserAgent); err != nil {
			return err
		}
	}

	if o.Format != nil {

		// query param format
		var qrFormat string

		if o.Format != nil {
			qrFormat = *o.Format
		}
		qFormat := qrFormat
		if qFormat != "" {

			if err := r.SetQueryParam("format", qFormat); err != nil {
				return err
			}
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
