// Code generated by go-swagger; DO NOT EDIT.

package lm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/logicmonitor/lm-sdk-go/v3/models"
)

// GetDeviceGroupClusterAlertConfListJSONReader is a Reader for the GetDeviceGroupClusterAlertConfListJSON structure.
type GetDeviceGroupClusterAlertConfListJSONReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDeviceGroupClusterAlertConfListJSONReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDeviceGroupClusterAlertConfListJSONOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 429:
		result := NewGetDeviceGroupClusterAlertConfListJSONTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetDeviceGroupClusterAlertConfListJSONDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetDeviceGroupClusterAlertConfListJSONOK creates a GetDeviceGroupClusterAlertConfListJSONOK with default headers values
func NewGetDeviceGroupClusterAlertConfListJSONOK() *GetDeviceGroupClusterAlertConfListJSONOK {
	return &GetDeviceGroupClusterAlertConfListJSONOK{}
}

/*
GetDeviceGroupClusterAlertConfListJSONOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetDeviceGroupClusterAlertConfListJSONOK struct {
	Payload interface{}
}

// IsSuccess returns true when this get device group cluster alert conf list Json o k response has a 2xx status code
func (o *GetDeviceGroupClusterAlertConfListJSONOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get device group cluster alert conf list Json o k response has a 3xx status code
func (o *GetDeviceGroupClusterAlertConfListJSONOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get device group cluster alert conf list Json o k response has a 4xx status code
func (o *GetDeviceGroupClusterAlertConfListJSONOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get device group cluster alert conf list Json o k response has a 5xx status code
func (o *GetDeviceGroupClusterAlertConfListJSONOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get device group cluster alert conf list Json o k response a status code equal to that given
func (o *GetDeviceGroupClusterAlertConfListJSONOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get device group cluster alert conf list Json o k response
func (o *GetDeviceGroupClusterAlertConfListJSONOK) Code() int {
	return 200
}

func (o *GetDeviceGroupClusterAlertConfListJSONOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /device/groups/{deviceGroupId}/clusterAlertConf?__json=][%d] getDeviceGroupClusterAlertConfListJsonOK %s", 200, payload)
}

func (o *GetDeviceGroupClusterAlertConfListJSONOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /device/groups/{deviceGroupId}/clusterAlertConf?__json=][%d] getDeviceGroupClusterAlertConfListJsonOK %s", 200, payload)
}

func (o *GetDeviceGroupClusterAlertConfListJSONOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetDeviceGroupClusterAlertConfListJSONOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDeviceGroupClusterAlertConfListJSONTooManyRequests creates a GetDeviceGroupClusterAlertConfListJSONTooManyRequests with default headers values
func NewGetDeviceGroupClusterAlertConfListJSONTooManyRequests() *GetDeviceGroupClusterAlertConfListJSONTooManyRequests {
	return &GetDeviceGroupClusterAlertConfListJSONTooManyRequests{}
}

/*
GetDeviceGroupClusterAlertConfListJSONTooManyRequests describes a response with status code 429, with default header values.

Too Many Requests
*/
type GetDeviceGroupClusterAlertConfListJSONTooManyRequests struct {

	/* Request limit per X-Rate-Limit-Window
	 */
	XRateLimitLimit int64

	/* The number of requests left for the time window
	 */
	XRateLimitRemaining int64

	/* The rolling time window length with the unit of second
	 */
	XRateLimitWindow int64
}

// IsSuccess returns true when this get device group cluster alert conf list Json too many requests response has a 2xx status code
func (o *GetDeviceGroupClusterAlertConfListJSONTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get device group cluster alert conf list Json too many requests response has a 3xx status code
func (o *GetDeviceGroupClusterAlertConfListJSONTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get device group cluster alert conf list Json too many requests response has a 4xx status code
func (o *GetDeviceGroupClusterAlertConfListJSONTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this get device group cluster alert conf list Json too many requests response has a 5xx status code
func (o *GetDeviceGroupClusterAlertConfListJSONTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this get device group cluster alert conf list Json too many requests response a status code equal to that given
func (o *GetDeviceGroupClusterAlertConfListJSONTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the get device group cluster alert conf list Json too many requests response
func (o *GetDeviceGroupClusterAlertConfListJSONTooManyRequests) Code() int {
	return 429
}

func (o *GetDeviceGroupClusterAlertConfListJSONTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /device/groups/{deviceGroupId}/clusterAlertConf?__json=][%d] getDeviceGroupClusterAlertConfListJsonTooManyRequests", 429)
}

func (o *GetDeviceGroupClusterAlertConfListJSONTooManyRequests) String() string {
	return fmt.Sprintf("[GET /device/groups/{deviceGroupId}/clusterAlertConf?__json=][%d] getDeviceGroupClusterAlertConfListJsonTooManyRequests", 429)
}

func (o *GetDeviceGroupClusterAlertConfListJSONTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-rate-limit-limit
	hdrXRateLimitLimit := response.GetHeader("x-rate-limit-limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("x-rate-limit-limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header x-rate-limit-remaining
	hdrXRateLimitRemaining := response.GetHeader("x-rate-limit-remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("x-rate-limit-remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	// hydrates response header x-rate-limit-window
	hdrXRateLimitWindow := response.GetHeader("x-rate-limit-window")

	if hdrXRateLimitWindow != "" {
		valxRateLimitWindow, err := swag.ConvertInt64(hdrXRateLimitWindow)
		if err != nil {
			return errors.InvalidType("x-rate-limit-window", "header", "int64", hdrXRateLimitWindow)
		}
		o.XRateLimitWindow = valxRateLimitWindow
	}

	return nil
}

// NewGetDeviceGroupClusterAlertConfListJSONDefault creates a GetDeviceGroupClusterAlertConfListJSONDefault with default headers values
func NewGetDeviceGroupClusterAlertConfListJSONDefault(code int) *GetDeviceGroupClusterAlertConfListJSONDefault {
	return &GetDeviceGroupClusterAlertConfListJSONDefault{
		_statusCode: code,
	}
}

/*
GetDeviceGroupClusterAlertConfListJSONDefault describes a response with status code -1, with default header values.

Error
*/
type GetDeviceGroupClusterAlertConfListJSONDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// IsSuccess returns true when this get device group cluster alert conf list Json default response has a 2xx status code
func (o *GetDeviceGroupClusterAlertConfListJSONDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get device group cluster alert conf list Json default response has a 3xx status code
func (o *GetDeviceGroupClusterAlertConfListJSONDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get device group cluster alert conf list Json default response has a 4xx status code
func (o *GetDeviceGroupClusterAlertConfListJSONDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get device group cluster alert conf list Json default response has a 5xx status code
func (o *GetDeviceGroupClusterAlertConfListJSONDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get device group cluster alert conf list Json default response a status code equal to that given
func (o *GetDeviceGroupClusterAlertConfListJSONDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get device group cluster alert conf list Json default response
func (o *GetDeviceGroupClusterAlertConfListJSONDefault) Code() int {
	return o._statusCode
}

func (o *GetDeviceGroupClusterAlertConfListJSONDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /device/groups/{deviceGroupId}/clusterAlertConf?__json=][%d] getDeviceGroupClusterAlertConfListJson default %s", o._statusCode, payload)
}

func (o *GetDeviceGroupClusterAlertConfListJSONDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /device/groups/{deviceGroupId}/clusterAlertConf?__json=][%d] getDeviceGroupClusterAlertConfListJson default %s", o._statusCode, payload)
}

func (o *GetDeviceGroupClusterAlertConfListJSONDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetDeviceGroupClusterAlertConfListJSONDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
