// Code generated by go-swagger; DO NOT EDIT.

package lm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/logicmonitor/lm-sdk-go/v3/models"
)

// GetDeviceDatasourceInstanceGroupByIDJSONReader is a Reader for the GetDeviceDatasourceInstanceGroupByIDJSON structure.
type GetDeviceDatasourceInstanceGroupByIDJSONReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDeviceDatasourceInstanceGroupByIDJSONReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDeviceDatasourceInstanceGroupByIDJSONOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 429:
		result := NewGetDeviceDatasourceInstanceGroupByIDJSONTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetDeviceDatasourceInstanceGroupByIDJSONDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetDeviceDatasourceInstanceGroupByIDJSONOK creates a GetDeviceDatasourceInstanceGroupByIDJSONOK with default headers values
func NewGetDeviceDatasourceInstanceGroupByIDJSONOK() *GetDeviceDatasourceInstanceGroupByIDJSONOK {
	return &GetDeviceDatasourceInstanceGroupByIDJSONOK{}
}

/*
GetDeviceDatasourceInstanceGroupByIDJSONOK describes a response with status code 200, with default header values.

successful operation
*/
type GetDeviceDatasourceInstanceGroupByIDJSONOK struct {
	Payload interface{}
}

// IsSuccess returns true when this get device datasource instance group by Id Json o k response has a 2xx status code
func (o *GetDeviceDatasourceInstanceGroupByIDJSONOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get device datasource instance group by Id Json o k response has a 3xx status code
func (o *GetDeviceDatasourceInstanceGroupByIDJSONOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get device datasource instance group by Id Json o k response has a 4xx status code
func (o *GetDeviceDatasourceInstanceGroupByIDJSONOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get device datasource instance group by Id Json o k response has a 5xx status code
func (o *GetDeviceDatasourceInstanceGroupByIDJSONOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get device datasource instance group by Id Json o k response a status code equal to that given
func (o *GetDeviceDatasourceInstanceGroupByIDJSONOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get device datasource instance group by Id Json o k response
func (o *GetDeviceDatasourceInstanceGroupByIDJSONOK) Code() int {
	return 200
}

func (o *GetDeviceDatasourceInstanceGroupByIDJSONOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /device/devices/{deviceId}/devicedatasources/{deviceDsId}/groups/{id}?__json=][%d] getDeviceDatasourceInstanceGroupByIdJsonOK %s", 200, payload)
}

func (o *GetDeviceDatasourceInstanceGroupByIDJSONOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /device/devices/{deviceId}/devicedatasources/{deviceDsId}/groups/{id}?__json=][%d] getDeviceDatasourceInstanceGroupByIdJsonOK %s", 200, payload)
}

func (o *GetDeviceDatasourceInstanceGroupByIDJSONOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetDeviceDatasourceInstanceGroupByIDJSONOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDeviceDatasourceInstanceGroupByIDJSONTooManyRequests creates a GetDeviceDatasourceInstanceGroupByIDJSONTooManyRequests with default headers values
func NewGetDeviceDatasourceInstanceGroupByIDJSONTooManyRequests() *GetDeviceDatasourceInstanceGroupByIDJSONTooManyRequests {
	return &GetDeviceDatasourceInstanceGroupByIDJSONTooManyRequests{}
}

/*
GetDeviceDatasourceInstanceGroupByIDJSONTooManyRequests describes a response with status code 429, with default header values.

Too Many Requests
*/
type GetDeviceDatasourceInstanceGroupByIDJSONTooManyRequests struct {

	/* Request limit per X-Rate-Limit-Window
	 */
	XRateLimitLimit int64

	/* The number of requests left for the time window
	 */
	XRateLimitRemaining int64

	/* The rolling time window length with the unit of second
	 */
	XRateLimitWindow int64
}

// IsSuccess returns true when this get device datasource instance group by Id Json too many requests response has a 2xx status code
func (o *GetDeviceDatasourceInstanceGroupByIDJSONTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get device datasource instance group by Id Json too many requests response has a 3xx status code
func (o *GetDeviceDatasourceInstanceGroupByIDJSONTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get device datasource instance group by Id Json too many requests response has a 4xx status code
func (o *GetDeviceDatasourceInstanceGroupByIDJSONTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this get device datasource instance group by Id Json too many requests response has a 5xx status code
func (o *GetDeviceDatasourceInstanceGroupByIDJSONTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this get device datasource instance group by Id Json too many requests response a status code equal to that given
func (o *GetDeviceDatasourceInstanceGroupByIDJSONTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the get device datasource instance group by Id Json too many requests response
func (o *GetDeviceDatasourceInstanceGroupByIDJSONTooManyRequests) Code() int {
	return 429
}

func (o *GetDeviceDatasourceInstanceGroupByIDJSONTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /device/devices/{deviceId}/devicedatasources/{deviceDsId}/groups/{id}?__json=][%d] getDeviceDatasourceInstanceGroupByIdJsonTooManyRequests", 429)
}

func (o *GetDeviceDatasourceInstanceGroupByIDJSONTooManyRequests) String() string {
	return fmt.Sprintf("[GET /device/devices/{deviceId}/devicedatasources/{deviceDsId}/groups/{id}?__json=][%d] getDeviceDatasourceInstanceGroupByIdJsonTooManyRequests", 429)
}

func (o *GetDeviceDatasourceInstanceGroupByIDJSONTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-rate-limit-limit
	hdrXRateLimitLimit := response.GetHeader("x-rate-limit-limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("x-rate-limit-limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header x-rate-limit-remaining
	hdrXRateLimitRemaining := response.GetHeader("x-rate-limit-remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("x-rate-limit-remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	// hydrates response header x-rate-limit-window
	hdrXRateLimitWindow := response.GetHeader("x-rate-limit-window")

	if hdrXRateLimitWindow != "" {
		valxRateLimitWindow, err := swag.ConvertInt64(hdrXRateLimitWindow)
		if err != nil {
			return errors.InvalidType("x-rate-limit-window", "header", "int64", hdrXRateLimitWindow)
		}
		o.XRateLimitWindow = valxRateLimitWindow
	}

	return nil
}

// NewGetDeviceDatasourceInstanceGroupByIDJSONDefault creates a GetDeviceDatasourceInstanceGroupByIDJSONDefault with default headers values
func NewGetDeviceDatasourceInstanceGroupByIDJSONDefault(code int) *GetDeviceDatasourceInstanceGroupByIDJSONDefault {
	return &GetDeviceDatasourceInstanceGroupByIDJSONDefault{
		_statusCode: code,
	}
}

/*
GetDeviceDatasourceInstanceGroupByIDJSONDefault describes a response with status code -1, with default header values.

Error
*/
type GetDeviceDatasourceInstanceGroupByIDJSONDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// IsSuccess returns true when this get device datasource instance group by Id Json default response has a 2xx status code
func (o *GetDeviceDatasourceInstanceGroupByIDJSONDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get device datasource instance group by Id Json default response has a 3xx status code
func (o *GetDeviceDatasourceInstanceGroupByIDJSONDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get device datasource instance group by Id Json default response has a 4xx status code
func (o *GetDeviceDatasourceInstanceGroupByIDJSONDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get device datasource instance group by Id Json default response has a 5xx status code
func (o *GetDeviceDatasourceInstanceGroupByIDJSONDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get device datasource instance group by Id Json default response a status code equal to that given
func (o *GetDeviceDatasourceInstanceGroupByIDJSONDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get device datasource instance group by Id Json default response
func (o *GetDeviceDatasourceInstanceGroupByIDJSONDefault) Code() int {
	return o._statusCode
}

func (o *GetDeviceDatasourceInstanceGroupByIDJSONDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /device/devices/{deviceId}/devicedatasources/{deviceDsId}/groups/{id}?__json=][%d] getDeviceDatasourceInstanceGroupByIdJson default %s", o._statusCode, payload)
}

func (o *GetDeviceDatasourceInstanceGroupByIDJSONDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /device/devices/{deviceId}/devicedatasources/{deviceDsId}/groups/{id}?__json=][%d] getDeviceDatasourceInstanceGroupByIdJson default %s", o._statusCode, payload)
}

func (o *GetDeviceDatasourceInstanceGroupByIDJSONDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetDeviceDatasourceInstanceGroupByIDJSONDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
