// Code generated by go-swagger; DO NOT EDIT.

package lm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/logicmonitor/lm-sdk-go/v3/models"
)

// GetWebsiteDataByGraphNameJSONReader is a Reader for the GetWebsiteDataByGraphNameJSON structure.
type GetWebsiteDataByGraphNameJSONReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWebsiteDataByGraphNameJSONReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetWebsiteDataByGraphNameJSONOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 429:
		result := NewGetWebsiteDataByGraphNameJSONTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetWebsiteDataByGraphNameJSONDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetWebsiteDataByGraphNameJSONOK creates a GetWebsiteDataByGraphNameJSONOK with default headers values
func NewGetWebsiteDataByGraphNameJSONOK() *GetWebsiteDataByGraphNameJSONOK {
	return &GetWebsiteDataByGraphNameJSONOK{}
}

/*
GetWebsiteDataByGraphNameJSONOK describes a response with status code 200, with default header values.

successful operation
*/
type GetWebsiteDataByGraphNameJSONOK struct {
	Payload interface{}
}

// IsSuccess returns true when this get website data by graph name Json o k response has a 2xx status code
func (o *GetWebsiteDataByGraphNameJSONOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get website data by graph name Json o k response has a 3xx status code
func (o *GetWebsiteDataByGraphNameJSONOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get website data by graph name Json o k response has a 4xx status code
func (o *GetWebsiteDataByGraphNameJSONOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get website data by graph name Json o k response has a 5xx status code
func (o *GetWebsiteDataByGraphNameJSONOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get website data by graph name Json o k response a status code equal to that given
func (o *GetWebsiteDataByGraphNameJSONOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get website data by graph name Json o k response
func (o *GetWebsiteDataByGraphNameJSONOK) Code() int {
	return 200
}

func (o *GetWebsiteDataByGraphNameJSONOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /website/websites/{id}/graphs/{graphName}/data?__json=][%d] getWebsiteDataByGraphNameJsonOK %s", 200, payload)
}

func (o *GetWebsiteDataByGraphNameJSONOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /website/websites/{id}/graphs/{graphName}/data?__json=][%d] getWebsiteDataByGraphNameJsonOK %s", 200, payload)
}

func (o *GetWebsiteDataByGraphNameJSONOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetWebsiteDataByGraphNameJSONOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetWebsiteDataByGraphNameJSONTooManyRequests creates a GetWebsiteDataByGraphNameJSONTooManyRequests with default headers values
func NewGetWebsiteDataByGraphNameJSONTooManyRequests() *GetWebsiteDataByGraphNameJSONTooManyRequests {
	return &GetWebsiteDataByGraphNameJSONTooManyRequests{}
}

/*
GetWebsiteDataByGraphNameJSONTooManyRequests describes a response with status code 429, with default header values.

Too Many Requests
*/
type GetWebsiteDataByGraphNameJSONTooManyRequests struct {

	/* Request limit per X-Rate-Limit-Window
	 */
	XRateLimitLimit int64

	/* The number of requests left for the time window
	 */
	XRateLimitRemaining int64

	/* The rolling time window length with the unit of second
	 */
	XRateLimitWindow int64
}

// IsSuccess returns true when this get website data by graph name Json too many requests response has a 2xx status code
func (o *GetWebsiteDataByGraphNameJSONTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get website data by graph name Json too many requests response has a 3xx status code
func (o *GetWebsiteDataByGraphNameJSONTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get website data by graph name Json too many requests response has a 4xx status code
func (o *GetWebsiteDataByGraphNameJSONTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this get website data by graph name Json too many requests response has a 5xx status code
func (o *GetWebsiteDataByGraphNameJSONTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this get website data by graph name Json too many requests response a status code equal to that given
func (o *GetWebsiteDataByGraphNameJSONTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the get website data by graph name Json too many requests response
func (o *GetWebsiteDataByGraphNameJSONTooManyRequests) Code() int {
	return 429
}

func (o *GetWebsiteDataByGraphNameJSONTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /website/websites/{id}/graphs/{graphName}/data?__json=][%d] getWebsiteDataByGraphNameJsonTooManyRequests", 429)
}

func (o *GetWebsiteDataByGraphNameJSONTooManyRequests) String() string {
	return fmt.Sprintf("[GET /website/websites/{id}/graphs/{graphName}/data?__json=][%d] getWebsiteDataByGraphNameJsonTooManyRequests", 429)
}

func (o *GetWebsiteDataByGraphNameJSONTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-rate-limit-limit
	hdrXRateLimitLimit := response.GetHeader("x-rate-limit-limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("x-rate-limit-limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header x-rate-limit-remaining
	hdrXRateLimitRemaining := response.GetHeader("x-rate-limit-remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("x-rate-limit-remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	// hydrates response header x-rate-limit-window
	hdrXRateLimitWindow := response.GetHeader("x-rate-limit-window")

	if hdrXRateLimitWindow != "" {
		valxRateLimitWindow, err := swag.ConvertInt64(hdrXRateLimitWindow)
		if err != nil {
			return errors.InvalidType("x-rate-limit-window", "header", "int64", hdrXRateLimitWindow)
		}
		o.XRateLimitWindow = valxRateLimitWindow
	}

	return nil
}

// NewGetWebsiteDataByGraphNameJSONDefault creates a GetWebsiteDataByGraphNameJSONDefault with default headers values
func NewGetWebsiteDataByGraphNameJSONDefault(code int) *GetWebsiteDataByGraphNameJSONDefault {
	return &GetWebsiteDataByGraphNameJSONDefault{
		_statusCode: code,
	}
}

/*
GetWebsiteDataByGraphNameJSONDefault describes a response with status code -1, with default header values.

Error
*/
type GetWebsiteDataByGraphNameJSONDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// IsSuccess returns true when this get website data by graph name Json default response has a 2xx status code
func (o *GetWebsiteDataByGraphNameJSONDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get website data by graph name Json default response has a 3xx status code
func (o *GetWebsiteDataByGraphNameJSONDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get website data by graph name Json default response has a 4xx status code
func (o *GetWebsiteDataByGraphNameJSONDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get website data by graph name Json default response has a 5xx status code
func (o *GetWebsiteDataByGraphNameJSONDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get website data by graph name Json default response a status code equal to that given
func (o *GetWebsiteDataByGraphNameJSONDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get website data by graph name Json default response
func (o *GetWebsiteDataByGraphNameJSONDefault) Code() int {
	return o._statusCode
}

func (o *GetWebsiteDataByGraphNameJSONDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /website/websites/{id}/graphs/{graphName}/data?__json=][%d] getWebsiteDataByGraphNameJson default %s", o._statusCode, payload)
}

func (o *GetWebsiteDataByGraphNameJSONDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /website/websites/{id}/graphs/{graphName}/data?__json=][%d] getWebsiteDataByGraphNameJson default %s", o._statusCode, payload)
}

func (o *GetWebsiteDataByGraphNameJSONDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetWebsiteDataByGraphNameJSONDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
