// Code generated by go-swagger; DO NOT EDIT.

package lm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetDashboardByIDJSONParams creates a new GetDashboardByIDJSONParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDashboardByIDJSONParams() *GetDashboardByIDJSONParams {
	return &GetDashboardByIDJSONParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDashboardByIDJSONParamsWithTimeout creates a new GetDashboardByIDJSONParams object
// with the ability to set a timeout on a request.
func NewGetDashboardByIDJSONParamsWithTimeout(timeout time.Duration) *GetDashboardByIDJSONParams {
	return &GetDashboardByIDJSONParams{
		timeout: timeout,
	}
}

// NewGetDashboardByIDJSONParamsWithContext creates a new GetDashboardByIDJSONParams object
// with the ability to set a context for a request.
func NewGetDashboardByIDJSONParamsWithContext(ctx context.Context) *GetDashboardByIDJSONParams {
	return &GetDashboardByIDJSONParams{
		Context: ctx,
	}
}

// NewGetDashboardByIDJSONParamsWithHTTPClient creates a new GetDashboardByIDJSONParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDashboardByIDJSONParamsWithHTTPClient(client *http.Client) *GetDashboardByIDJSONParams {
	return &GetDashboardByIDJSONParams{
		HTTPClient: client,
	}
}

/*
GetDashboardByIDJSONParams contains all the parameters to send to the API endpoint

	for the get dashboard by Id Json operation.

	Typically these are written to a http.Request.
*/
type GetDashboardByIDJSONParams struct {

	// UserAgent.
	//
	// Default: "Logicmonitor/GO-SDK"
	UserAgent *string

	// Fields.
	Fields *string

	// Format.
	//
	// Default: "json"
	Format *string

	// ID.
	//
	// Format: int32
	ID int32

	// Template.
	Template *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get dashboard by Id Json params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDashboardByIDJSONParams) WithDefaults() *GetDashboardByIDJSONParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get dashboard by Id Json params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDashboardByIDJSONParams) SetDefaults() {
	var (
		userAgentDefault = string("Logicmonitor/GO-SDK")

		formatDefault = string("json")

		templateDefault = bool(false)
	)

	val := GetDashboardByIDJSONParams{
		UserAgent: &userAgentDefault,
		Format:    &formatDefault,
		Template:  &templateDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get dashboard by Id Json params
func (o *GetDashboardByIDJSONParams) WithTimeout(timeout time.Duration) *GetDashboardByIDJSONParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get dashboard by Id Json params
func (o *GetDashboardByIDJSONParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get dashboard by Id Json params
func (o *GetDashboardByIDJSONParams) WithContext(ctx context.Context) *GetDashboardByIDJSONParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get dashboard by Id Json params
func (o *GetDashboardByIDJSONParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get dashboard by Id Json params
func (o *GetDashboardByIDJSONParams) WithHTTPClient(client *http.Client) *GetDashboardByIDJSONParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get dashboard by Id Json params
func (o *GetDashboardByIDJSONParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserAgent adds the userAgent to the get dashboard by Id Json params
func (o *GetDashboardByIDJSONParams) WithUserAgent(userAgent *string) *GetDashboardByIDJSONParams {
	o.SetUserAgent(userAgent)
	return o
}

// SetUserAgent adds the userAgent to the get dashboard by Id Json params
func (o *GetDashboardByIDJSONParams) SetUserAgent(userAgent *string) {
	o.UserAgent = userAgent
}

// WithFields adds the fields to the get dashboard by Id Json params
func (o *GetDashboardByIDJSONParams) WithFields(fields *string) *GetDashboardByIDJSONParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get dashboard by Id Json params
func (o *GetDashboardByIDJSONParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithFormat adds the format to the get dashboard by Id Json params
func (o *GetDashboardByIDJSONParams) WithFormat(format *string) *GetDashboardByIDJSONParams {
	o.SetFormat(format)
	return o
}

// SetFormat adds the format to the get dashboard by Id Json params
func (o *GetDashboardByIDJSONParams) SetFormat(format *string) {
	o.Format = format
}

// WithID adds the id to the get dashboard by Id Json params
func (o *GetDashboardByIDJSONParams) WithID(id int32) *GetDashboardByIDJSONParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get dashboard by Id Json params
func (o *GetDashboardByIDJSONParams) SetID(id int32) {
	o.ID = id
}

// WithTemplate adds the template to the get dashboard by Id Json params
func (o *GetDashboardByIDJSONParams) WithTemplate(template *bool) *GetDashboardByIDJSONParams {
	o.SetTemplate(template)
	return o
}

// SetTemplate adds the template to the get dashboard by Id Json params
func (o *GetDashboardByIDJSONParams) SetTemplate(template *bool) {
	o.Template = template
}

// WriteToRequest writes these params to a swagger request
func (o *GetDashboardByIDJSONParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.UserAgent != nil {

		// header param User-Agent
		if err := r.SetHeaderParam("User-Agent", *o.UserAgent); err != nil {
			return err
		}
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	if o.Format != nil {

		// query param format
		var qrFormat string

		if o.Format != nil {
			qrFormat = *o.Format
		}
		qFormat := qrFormat
		if qFormat != "" {

			if err := r.SetQueryParam("format", qFormat); err != nil {
				return err
			}
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if o.Template != nil {

		// query param template
		var qrTemplate bool

		if o.Template != nil {
			qrTemplate = *o.Template
		}
		qTemplate := swag.FormatBool(qrTemplate)
		if qTemplate != "" {

			if err := r.SetQueryParam("template", qTemplate); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
