// Code generated by go-swagger; DO NOT EDIT.

package lm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/logicmonitor/lm-sdk-go/v3/models"
)

// MapUnMapModuleToAccessGroupReader is a Reader for the MapUnMapModuleToAccessGroup structure.
type MapUnMapModuleToAccessGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MapUnMapModuleToAccessGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMapUnMapModuleToAccessGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 429:
		result := NewMapUnMapModuleToAccessGroupTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewMapUnMapModuleToAccessGroupDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewMapUnMapModuleToAccessGroupOK creates a MapUnMapModuleToAccessGroupOK with default headers values
func NewMapUnMapModuleToAccessGroupOK() *MapUnMapModuleToAccessGroupOK {
	return &MapUnMapModuleToAccessGroupOK{}
}

/*
MapUnMapModuleToAccessGroupOK describes a response with status code 200, with default header values.

Successfully created the mapping
*/
type MapUnMapModuleToAccessGroupOK struct {
	Payload *models.RestMapModuleV3
}

// IsSuccess returns true when this map un map module to access group o k response has a 2xx status code
func (o *MapUnMapModuleToAccessGroupOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this map un map module to access group o k response has a 3xx status code
func (o *MapUnMapModuleToAccessGroupOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this map un map module to access group o k response has a 4xx status code
func (o *MapUnMapModuleToAccessGroupOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this map un map module to access group o k response has a 5xx status code
func (o *MapUnMapModuleToAccessGroupOK) IsServerError() bool {
	return false
}

// IsCode returns true when this map un map module to access group o k response a status code equal to that given
func (o *MapUnMapModuleToAccessGroupOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the map un map module to access group o k response
func (o *MapUnMapModuleToAccessGroupOK) Code() int {
	return 200
}

func (o *MapUnMapModuleToAccessGroupOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /setting/accessgroup/mapunmap/modules][%d] mapUnMapModuleToAccessGroupOK %s", 200, payload)
}

func (o *MapUnMapModuleToAccessGroupOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /setting/accessgroup/mapunmap/modules][%d] mapUnMapModuleToAccessGroupOK %s", 200, payload)
}

func (o *MapUnMapModuleToAccessGroupOK) GetPayload() *models.RestMapModuleV3 {
	return o.Payload
}

func (o *MapUnMapModuleToAccessGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestMapModuleV3)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMapUnMapModuleToAccessGroupTooManyRequests creates a MapUnMapModuleToAccessGroupTooManyRequests with default headers values
func NewMapUnMapModuleToAccessGroupTooManyRequests() *MapUnMapModuleToAccessGroupTooManyRequests {
	return &MapUnMapModuleToAccessGroupTooManyRequests{}
}

/*
MapUnMapModuleToAccessGroupTooManyRequests describes a response with status code 429, with default header values.

Too Many Requests
*/
type MapUnMapModuleToAccessGroupTooManyRequests struct {

	/* Request limit per X-Rate-Limit-Window
	 */
	XRateLimitLimit int64

	/* The number of requests left for the time window
	 */
	XRateLimitRemaining int64

	/* The rolling time window length with the unit of second
	 */
	XRateLimitWindow int64
}

// IsSuccess returns true when this map un map module to access group too many requests response has a 2xx status code
func (o *MapUnMapModuleToAccessGroupTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this map un map module to access group too many requests response has a 3xx status code
func (o *MapUnMapModuleToAccessGroupTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this map un map module to access group too many requests response has a 4xx status code
func (o *MapUnMapModuleToAccessGroupTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this map un map module to access group too many requests response has a 5xx status code
func (o *MapUnMapModuleToAccessGroupTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this map un map module to access group too many requests response a status code equal to that given
func (o *MapUnMapModuleToAccessGroupTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the map un map module to access group too many requests response
func (o *MapUnMapModuleToAccessGroupTooManyRequests) Code() int {
	return 429
}

func (o *MapUnMapModuleToAccessGroupTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /setting/accessgroup/mapunmap/modules][%d] mapUnMapModuleToAccessGroupTooManyRequests", 429)
}

func (o *MapUnMapModuleToAccessGroupTooManyRequests) String() string {
	return fmt.Sprintf("[POST /setting/accessgroup/mapunmap/modules][%d] mapUnMapModuleToAccessGroupTooManyRequests", 429)
}

func (o *MapUnMapModuleToAccessGroupTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-rate-limit-limit
	hdrXRateLimitLimit := response.GetHeader("x-rate-limit-limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("x-rate-limit-limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header x-rate-limit-remaining
	hdrXRateLimitRemaining := response.GetHeader("x-rate-limit-remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("x-rate-limit-remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	// hydrates response header x-rate-limit-window
	hdrXRateLimitWindow := response.GetHeader("x-rate-limit-window")

	if hdrXRateLimitWindow != "" {
		valxRateLimitWindow, err := swag.ConvertInt64(hdrXRateLimitWindow)
		if err != nil {
			return errors.InvalidType("x-rate-limit-window", "header", "int64", hdrXRateLimitWindow)
		}
		o.XRateLimitWindow = valxRateLimitWindow
	}

	return nil
}

// NewMapUnMapModuleToAccessGroupDefault creates a MapUnMapModuleToAccessGroupDefault with default headers values
func NewMapUnMapModuleToAccessGroupDefault(code int) *MapUnMapModuleToAccessGroupDefault {
	return &MapUnMapModuleToAccessGroupDefault{
		_statusCode: code,
	}
}

/*
MapUnMapModuleToAccessGroupDefault describes a response with status code -1, with default header values.

Error
*/
type MapUnMapModuleToAccessGroupDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// IsSuccess returns true when this map un map module to access group default response has a 2xx status code
func (o *MapUnMapModuleToAccessGroupDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this map un map module to access group default response has a 3xx status code
func (o *MapUnMapModuleToAccessGroupDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this map un map module to access group default response has a 4xx status code
func (o *MapUnMapModuleToAccessGroupDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this map un map module to access group default response has a 5xx status code
func (o *MapUnMapModuleToAccessGroupDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this map un map module to access group default response a status code equal to that given
func (o *MapUnMapModuleToAccessGroupDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the map un map module to access group default response
func (o *MapUnMapModuleToAccessGroupDefault) Code() int {
	return o._statusCode
}

func (o *MapUnMapModuleToAccessGroupDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /setting/accessgroup/mapunmap/modules][%d] mapUnMapModuleToAccessGroup default %s", o._statusCode, payload)
}

func (o *MapUnMapModuleToAccessGroupDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /setting/accessgroup/mapunmap/modules][%d] mapUnMapModuleToAccessGroup default %s", o._statusCode, payload)
}

func (o *MapUnMapModuleToAccessGroupDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *MapUnMapModuleToAccessGroupDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
