// Code generated by go-swagger; DO NOT EDIT.

package lm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/logicmonitor/lm-sdk-go/v3/models"
)

// NewPatchRemediationSourceByIDParams creates a new PatchRemediationSourceByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchRemediationSourceByIDParams() *PatchRemediationSourceByIDParams {
	return &PatchRemediationSourceByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchRemediationSourceByIDParamsWithTimeout creates a new PatchRemediationSourceByIDParams object
// with the ability to set a timeout on a request.
func NewPatchRemediationSourceByIDParamsWithTimeout(timeout time.Duration) *PatchRemediationSourceByIDParams {
	return &PatchRemediationSourceByIDParams{
		timeout: timeout,
	}
}

// NewPatchRemediationSourceByIDParamsWithContext creates a new PatchRemediationSourceByIDParams object
// with the ability to set a context for a request.
func NewPatchRemediationSourceByIDParamsWithContext(ctx context.Context) *PatchRemediationSourceByIDParams {
	return &PatchRemediationSourceByIDParams{
		Context: ctx,
	}
}

// NewPatchRemediationSourceByIDParamsWithHTTPClient creates a new PatchRemediationSourceByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchRemediationSourceByIDParamsWithHTTPClient(client *http.Client) *PatchRemediationSourceByIDParams {
	return &PatchRemediationSourceByIDParams{
		HTTPClient: client,
	}
}

/*
PatchRemediationSourceByIDParams contains all the parameters to send to the API endpoint

	for the patch remediation source by Id operation.

	Typically these are written to a http.Request.
*/
type PatchRemediationSourceByIDParams struct {

	// UserAgent.
	//
	// Default: "Logicmonitor/GO-SDK"
	UserAgent *string

	// Body.
	Body *models.RemediationSource

	// ID.
	//
	// Format: int32
	ID int32

	// Reason.
	Reason *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch remediation source by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchRemediationSourceByIDParams) WithDefaults() *PatchRemediationSourceByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch remediation source by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchRemediationSourceByIDParams) SetDefaults() {
	var (
		userAgentDefault = string("Logicmonitor/GO-SDK")
	)

	val := PatchRemediationSourceByIDParams{
		UserAgent: &userAgentDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the patch remediation source by Id params
func (o *PatchRemediationSourceByIDParams) WithTimeout(timeout time.Duration) *PatchRemediationSourceByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch remediation source by Id params
func (o *PatchRemediationSourceByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch remediation source by Id params
func (o *PatchRemediationSourceByIDParams) WithContext(ctx context.Context) *PatchRemediationSourceByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch remediation source by Id params
func (o *PatchRemediationSourceByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch remediation source by Id params
func (o *PatchRemediationSourceByIDParams) WithHTTPClient(client *http.Client) *PatchRemediationSourceByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch remediation source by Id params
func (o *PatchRemediationSourceByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserAgent adds the userAgent to the patch remediation source by Id params
func (o *PatchRemediationSourceByIDParams) WithUserAgent(userAgent *string) *PatchRemediationSourceByIDParams {
	o.SetUserAgent(userAgent)
	return o
}

// SetUserAgent adds the userAgent to the patch remediation source by Id params
func (o *PatchRemediationSourceByIDParams) SetUserAgent(userAgent *string) {
	o.UserAgent = userAgent
}

// WithBody adds the body to the patch remediation source by Id params
func (o *PatchRemediationSourceByIDParams) WithBody(body *models.RemediationSource) *PatchRemediationSourceByIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch remediation source by Id params
func (o *PatchRemediationSourceByIDParams) SetBody(body *models.RemediationSource) {
	o.Body = body
}

// WithID adds the id to the patch remediation source by Id params
func (o *PatchRemediationSourceByIDParams) WithID(id int32) *PatchRemediationSourceByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch remediation source by Id params
func (o *PatchRemediationSourceByIDParams) SetID(id int32) {
	o.ID = id
}

// WithReason adds the reason to the patch remediation source by Id params
func (o *PatchRemediationSourceByIDParams) WithReason(reason *string) *PatchRemediationSourceByIDParams {
	o.SetReason(reason)
	return o
}

// SetReason adds the reason to the patch remediation source by Id params
func (o *PatchRemediationSourceByIDParams) SetReason(reason *string) {
	o.Reason = reason
}

// WriteToRequest writes these params to a swagger request
func (o *PatchRemediationSourceByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.UserAgent != nil {

		// header param User-Agent
		if err := r.SetHeaderParam("User-Agent", *o.UserAgent); err != nil {
			return err
		}
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if o.Reason != nil {

		// query param reason
		var qrReason string

		if o.Reason != nil {
			qrReason = *o.Reason
		}
		qReason := qrReason
		if qReason != "" {

			if err := r.SetQueryParam("reason", qReason); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
