// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RestNetscanPorts rest netscan ports
//
// swagger:model RestNetscanPorts
type RestNetscanPorts struct {

	// Whether or not default ports should be used
	// Example: true
	IsGlobalDefault bool `json:"isGlobalDefault,omitempty"`

	// The ports that should be used in the Netscan
	// Example: 21,22,23
	Value string `json:"value,omitempty"`
}

// Validate validates this rest netscan ports
func (m *RestNetscanPorts) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this rest netscan ports based on context it is used
func (m *RestNetscanPorts) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RestNetscanPorts) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RestNetscanPorts) UnmarshalBinary(b []byte) error {
	var res RestNetscanPorts
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
