// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SaasO365SkusDiscoveryMethod saas o365 skus discovery method
//
// swagger:model SaasO365SkusDiscoveryMethod
type SaasO365SkusDiscoveryMethod struct {
	SaasO365SkusDiscoveryMethodAllOf1
}

// Name gets the name of this subtype
func (m *SaasO365SkusDiscoveryMethod) Name() string {
	return "SaasO365SkusDiscoveryMethod"
}

// SetName sets the name of this subtype
func (m *SaasO365SkusDiscoveryMethod) SetName(val string) {
}

// UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
func (m *SaasO365SkusDiscoveryMethod) UnmarshalJSON(raw []byte) error {
	var data struct {
		SaasO365SkusDiscoveryMethodAllOf1
	}
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	var base struct {
		/* Just the base type fields. Used for unmashalling polymorphic types.*/

		Name string `json:"name"`
	}
	buf = bytes.NewBuffer(raw)
	dec = json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&base); err != nil {
		return err
	}

	var result SaasO365SkusDiscoveryMethod

	if base.Name != result.Name() {
		/* Not the type we're looking for. */
		return errors.New(422, "invalid name value: %q", base.Name)
	}
	result.SaasO365SkusDiscoveryMethodAllOf1 = data.SaasO365SkusDiscoveryMethodAllOf1

	*m = result

	return nil
}

// MarshalJSON marshals this object with a polymorphic type to a JSON structure
func (m SaasO365SkusDiscoveryMethod) MarshalJSON() ([]byte, error) {
	var b1, b2, b3 []byte
	var err error
	b1, err = json.Marshal(struct {
		SaasO365SkusDiscoveryMethodAllOf1
	}{

		SaasO365SkusDiscoveryMethodAllOf1: m.SaasO365SkusDiscoveryMethodAllOf1,
	})
	if err != nil {
		return nil, err
	}
	b2, err = json.Marshal(struct {
		Name string `json:"name"`
	}{

		Name: m.Name(),
	})
	if err != nil {
		return nil, err
	}

	return swag.ConcatJSON(b1, b2, b3), nil
}

// Validate validates this saas o365 skus discovery method
func (m *SaasO365SkusDiscoveryMethod) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with SaasO365SkusDiscoveryMethodAllOf1

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this saas o365 skus discovery method based on the context it is used
func (m *SaasO365SkusDiscoveryMethod) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with SaasO365SkusDiscoveryMethodAllOf1

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *SaasO365SkusDiscoveryMethod) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SaasO365SkusDiscoveryMethod) UnmarshalBinary(b []byte) error {
	var res SaasO365SkusDiscoveryMethod
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// SaasO365SkusDiscoveryMethodAllOf1 saas o365 skus discovery method all of1
//
// swagger:model SaasO365SkusDiscoveryMethodAllOf1
type SaasO365SkusDiscoveryMethodAllOf1 interface{}
