// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EventSourceFilter event source filter
//
// swagger:model EventSourceFilter
type EventSourceFilter struct {

	// comment
	Comment string `json:"comment,omitempty"`

	// event source Id
	EventSourceID int32 `json:"eventSourceId,omitempty"`

	// id
	ID int32 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// op
	Op string `json:"op,omitempty"`

	// origin Id
	OriginID string `json:"originId,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this event source filter
func (m *EventSourceFilter) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this event source filter based on context it is used
func (m *EventSourceFilter) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EventSourceFilter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EventSourceFilter) UnmarshalBinary(b []byte) error {
	var res EventSourceFilter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
