// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GcpVpnTunnelDiscoveryMethodV3 gcp vpn tunnel discovery method v3
//
// swagger:model GcpVpnTunnelDiscoveryMethodV3
type GcpVpnTunnelDiscoveryMethodV3 struct {
	GcpVpnTunnelDiscoveryMethodV3AllOf1
}

// Name gets the name of this subtype
func (m *GcpVpnTunnelDiscoveryMethodV3) Name() string {
	return "GcpVpnTunnelDiscoveryMethodV3"
}

// SetName sets the name of this subtype
func (m *GcpVpnTunnelDiscoveryMethodV3) SetName(val string) {
}

// UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
func (m *GcpVpnTunnelDiscoveryMethodV3) UnmarshalJSON(raw []byte) error {
	var data struct {
		GcpVpnTunnelDiscoveryMethodV3AllOf1
	}
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	var base struct {
		/* Just the base type fields. Used for unmashalling polymorphic types.*/

		Name string `json:"name"`
	}
	buf = bytes.NewBuffer(raw)
	dec = json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&base); err != nil {
		return err
	}

	var result GcpVpnTunnelDiscoveryMethodV3

	if base.Name != result.Name() {
		/* Not the type we're looking for. */
		return errors.New(422, "invalid name value: %q", base.Name)
	}
	result.GcpVpnTunnelDiscoveryMethodV3AllOf1 = data.GcpVpnTunnelDiscoveryMethodV3AllOf1

	*m = result

	return nil
}

// MarshalJSON marshals this object with a polymorphic type to a JSON structure
func (m GcpVpnTunnelDiscoveryMethodV3) MarshalJSON() ([]byte, error) {
	var b1, b2, b3 []byte
	var err error
	b1, err = json.Marshal(struct {
		GcpVpnTunnelDiscoveryMethodV3AllOf1
	}{

		GcpVpnTunnelDiscoveryMethodV3AllOf1: m.GcpVpnTunnelDiscoveryMethodV3AllOf1,
	})
	if err != nil {
		return nil, err
	}
	b2, err = json.Marshal(struct {
		Name string `json:"name"`
	}{

		Name: m.Name(),
	})
	if err != nil {
		return nil, err
	}

	return swag.ConcatJSON(b1, b2, b3), nil
}

// Validate validates this gcp vpn tunnel discovery method v3
func (m *GcpVpnTunnelDiscoveryMethodV3) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with GcpVpnTunnelDiscoveryMethodV3AllOf1

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this gcp vpn tunnel discovery method v3 based on the context it is used
func (m *GcpVpnTunnelDiscoveryMethodV3) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with GcpVpnTunnelDiscoveryMethodV3AllOf1

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *GcpVpnTunnelDiscoveryMethodV3) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GcpVpnTunnelDiscoveryMethodV3) UnmarshalBinary(b []byte) error {
	var res GcpVpnTunnelDiscoveryMethodV3
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// GcpVpnTunnelDiscoveryMethodV3AllOf1 gcp vpn tunnel discovery method v3 all of1
//
// swagger:model GcpVpnTunnelDiscoveryMethodV3AllOf1
type GcpVpnTunnelDiscoveryMethodV3AllOf1 interface{}
