// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RemediationSourceExecution Represents a remediation execution for a host in the LogicMonitor system.
//
// swagger:model RemediationSourceExecution
type RemediationSourceExecution struct {

	// The alert id
	// Example: alert12345
	// Required: true
	AlertID *string `json:"alertId"`

	// execution Id
	// Read Only: true
	ExecutionID string `json:"executionId,omitempty"`

	// The remediation module id
	// Example: 60
	// Required: true
	// Read Only: true
	ExecutionStatus string `json:"executionStatus"`

	// The host id
	// Example: 12345
	// Required: true
	HostID *int32 `json:"hostId"`

	// The remediation module id
	// Example: 12345
	// Required: true
	HostRemediationSourceID *int64 `json:"hostRemediationSourceId"`

	// The remediation module id
	// Example: 12345
	// Required: true
	RemediationID *int32 `json:"remediationId"`

	// type of trigger
	// Example: scheduled
	// Required: true
	// Read Only: true
	TriggerType string `json:"triggerType"`
}

// Validate validates this remediation source execution
func (m *RemediationSourceExecution) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAlertID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExecutionStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHostID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHostRemediationSourceID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRemediationID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTriggerType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RemediationSourceExecution) validateAlertID(formats strfmt.Registry) error {

	if err := validate.Required("alertId", "body", m.AlertID); err != nil {
		return err
	}

	return nil
}

func (m *RemediationSourceExecution) validateExecutionStatus(formats strfmt.Registry) error {

	if err := validate.RequiredString("executionStatus", "body", m.ExecutionStatus); err != nil {
		return err
	}

	return nil
}

func (m *RemediationSourceExecution) validateHostID(formats strfmt.Registry) error {

	if err := validate.Required("hostId", "body", m.HostID); err != nil {
		return err
	}

	return nil
}

func (m *RemediationSourceExecution) validateHostRemediationSourceID(formats strfmt.Registry) error {

	if err := validate.Required("hostRemediationSourceId", "body", m.HostRemediationSourceID); err != nil {
		return err
	}

	return nil
}

func (m *RemediationSourceExecution) validateRemediationID(formats strfmt.Registry) error {

	if err := validate.Required("remediationId", "body", m.RemediationID); err != nil {
		return err
	}

	return nil
}

func (m *RemediationSourceExecution) validateTriggerType(formats strfmt.Registry) error {

	if err := validate.RequiredString("triggerType", "body", m.TriggerType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this remediation source execution based on the context it is used
func (m *RemediationSourceExecution) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateExecutionID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateExecutionStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTriggerType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RemediationSourceExecution) contextValidateExecutionID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "executionId", "body", string(m.ExecutionID)); err != nil {
		return err
	}

	return nil
}

func (m *RemediationSourceExecution) contextValidateExecutionStatus(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "executionStatus", "body", string(m.ExecutionStatus)); err != nil {
		return err
	}

	return nil
}

func (m *RemediationSourceExecution) contextValidateTriggerType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "triggerType", "body", string(m.TriggerType)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RemediationSourceExecution) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RemediationSourceExecution) UnmarshalBinary(b []byte) error {
	var res RemediationSourceExecution
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
