// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RestResponseMetaBlock rest response meta block
//
// swagger:model RestResponseMetaBlock
type RestResponseMetaBlock struct {

	// filtered count
	FilteredCount int64 `json:"filteredCount,omitempty"`

	// page offset count
	PageOffsetCount int32 `json:"pageOffsetCount,omitempty"`

	// per page count
	PerPageCount int32 `json:"perPageCount,omitempty"`

	// sort
	Sort string `json:"sort,omitempty"`

	// total count
	TotalCount int64 `json:"totalCount,omitempty"`
}

// Validate validates this rest response meta block
func (m *RestResponseMetaBlock) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this rest response meta block based on context it is used
func (m *RestResponseMetaBlock) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RestResponseMetaBlock) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RestResponseMetaBlock) UnmarshalBinary(b []byte) error {
	var res RestResponseMetaBlock
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
